# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bundle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bundle

  pod 'Firebase/Core'
  pod ‘Firebase/Auth’
  pod ‘Firebase/Database’


  target 'BundleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BundleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
